# Generated by Django 5.1.6 on 2025-02-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0002_faculty_alter_student_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='rollno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
