# Generated by Django 5.1.6 on 2025-02-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0003_rename_student_id_student_rollno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
