# Generated by Django 5.1.6 on 2025-02-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0005_alter_student_class_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Childrens',
        ),
    ]
