# Generated by Django 5.1.6 on 2025-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0007_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('hod_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
