# Generated by Django 5.1.6 on 2025-03-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0010_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrens',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childrens',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='childrens',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
