# Generated by Django 5.1.6 on 2025-03-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0011_childrens_address_childrens_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrens',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
