# Generated by Django 5.1.6 on 2025-03-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0012_childrens_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrens',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='controll.hod'),
        ),
    ]
