# Generated by Django 5.1.6 on 2025-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0013_childrens_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Class Time Table', max_length=255)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('slot_1', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_2', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_3', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_4', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_5', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_6', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_7', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
