# Generated by Django 5.1.6 on 2025-03-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0015_leaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('MBA', 'MBA')], max_length=3)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6')], max_length=1)),
            ],
        ),
    ]
