# Generated by Django 5.1.6 on 2025-03-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0017_alter_subject_department_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
    ]
