# Generated by Django 5.1.6 on 2025-03-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0018_remove_marks_total_marks_marks_max_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
