# Generated by Django 5.1.6 on 2025-04-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0019_marks_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controll.faculty')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controll.hod')),
            ],
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
