# Generated by Django 5.1.6 on 2025-04-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0020_facultyleaveapplication_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controll.childrens')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controll.subject')),
            ],
        ),
    ]
