"""
Django settings for college project.
Generated by 'django-admin startproject' using Django 5.1.6.
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key

# 📂 Project Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 Security Key
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', get_random_secret_key())

# 🚨 Debug Mode (Set False in Production)
DEBUG = True

# 🌍 Allowed Hosts (Add your domain in production)
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# 📌 Installed Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ✅ Your Apps
    'controll',
    'student',
    'HOD',
    'faculty',  # ✅ Add this line
]


# 🔄 Middleware (Ensure Security & Session Middleware are Included)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # ✅ Required for session management
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # ✅ Required for authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔀 Root URL Configuration
ROOT_URLCONF = 'college.urls'

# 🎨 Templates Configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # This includes a global templates folder
        ],
        'APP_DIRS': True,  # Tells Django to look in each app's templates folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🚀 WSGI Application
WSGI_APPLICATION = 'college.wsgi.application'

# 🗄️ Database Configuration (Change for Production)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔑 Authentication & Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌍 Internationalization & Time Settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # ✅ Updated for India timezone (Change if needed)
USE_I18N = True
USE_TZ = True

# 🎨 Static & Media Files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # ✅ Ensure 'static' folder exists
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 🖼️ Media Files Configuration (For Profile Photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 🔄 Authentication Redirects
LOGIN_URL = 'login'  # ✅ Ensure 'login' URL exists in urls.py
LOGIN_REDIRECT_URL = 'admin_home'  # ✅ Ensure 'admin_home' is a valid URL name
LOGOUT_REDIRECT_URL = 'login'

# 🔄 Session Management
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # ✅ Store sessions in the database
SESSION_COOKIE_AGE = 86400  # ✅ Session lasts 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # ✅ Keeps session active after browser closes
SESSION_COOKIE_SECURE = False  # ✅ Set to True only for HTTPS

# 🔐 Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ Serving Media Files During Development
if DEBUG:
    from django.conf.urls.static import static
    urlpatterns = static(MEDIA_URL, document_root=MEDIA_ROOT)

